# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hello-Jenkins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello-Jenkins
  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'Hello-JenkinsTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'Hello-JenkinsUITests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

end
